# Generated by Django 3.2.4 on 2021-06-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberssssq',
            name='shirt_company',
            field=models.CharField(choices=[('Air', 'AirBnB'), ('AOL', 'AOL'), ('App', 'Apple')], default='App', max_length=3),
        ),
    ]
