# Generated by Django 3.2.4 on 2021-06-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_numberssssq_shirt_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberssssq',
            name='number_phonesq',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='numberssssq',
            name='price_rubsq',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='numberssssq',
            name='price_usasq',
            field=models.CharField(max_length=100),
        ),
    ]
