# Generated by Django 3.2.4 on 2021-06-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_phone_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberssssq',
            name='shirt_company',
            field=models.CharField(choices=[('1St', '1StopMove'), ('Abr', 'AccountPatrol'), ('Aff', 'Affirm'), ('Aft', 'AfterPay'), ('Air', 'AirBnB'), ('Alb', 'Albert'), ('ALI', 'Alibaba'), ('AMA', 'Amazon'), ('AND', 'Ando'), ('AOL', 'AOL'), ('APP', 'Apple'), ('AT&', 'AT&T'), ('ATO', 'Atom'), ('AAXO', 'AxosBank'), ('BAN', 'Banxa'), ('BAN', 'Banq'), ('BAS', 'BaskBank'), ('BB&', 'BB&T'), ('BBV', 'BBVA'), ('BEF', 'BeFrugal'), ('BET', 'Betterment'), ('BES', 'BestBuy'), ('BIG', 'BigoLive'), ('BIT', 'Bit2Me'), ('BIN', 'Binance'), ('BIY', 'BitFlyer'), ('BIL', 'BitLeague'), ('BIM', 'Bitmo'), ('BIR', 'Bitfront'), ('BLA', 'BlackPeopleMeet'), ('BIA', 'Bitstamp'), ('BLV', 'BlueVine'), ('BLO', 'BlockFi'), ('BOF', 'BOFA'), ('BOO', 'Booking'), ('BOS', 'Boss'), ('BOX', 'BoxyPay'), ('BRE', 'Brex'), ('BRA', 'Bread'), ('BUD', 'Bundil'), ('BUN', 'BunQ'), ('BUR', 'Burner'), ('CAP', 'CapitalOne'), ('CAR', 'CardCookie'), ('CAD', 'CardDelivery'), ('CSH', 'CashApp'), ('CDK', 'CDkeys'), ('CEX', 'Cex.io'), ('CHA', 'Chase'), ('CHB', 'CheckBook'), ('CHM', 'Chemistry'), ('CHI', 'Chime'), ('CIR', 'Circle'), ('CIT', 'CITBank'), ('CIB', 'CitiBank'), ('CJS', 'cjsCDkeys'), ('COG', 'Cogni'), ('CON', 'CoinBase'), ('COD', 'CoinField'), ('COP', 'CoinFlip'), ('COH', 'CoinHouseSAS'), ('COS', 'CoinsBank')], default='App', max_length=15),
        ),
    ]
