# Generated by Django 3.2.4 on 2021-06-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210612_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberssssq',
            name='shirt_company',
            field=models.CharField(choices=[('AirBNB', 'AirBNB'), ('2Game', '2Game'), ('gfhf', 'gfhf')], default='App', max_length=15),
        ),
    ]
