# Generated by Django 3.2 on 2021-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_numbers_of_phone_sms_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberssssq',
            name='shirt_limit',
            field=models.CharField(choices=[('Отключен', 'Отключен'), ('1 день', '1 день'), ('3 дня', '3 дня'), ('1 неделя', '1 неделя'), ('2 недели', '2 недели'), ('1 месяц', '1 месяц'), ('2 месяца', '2 месяца')], default='Отключен', max_length=15),
        ),
    ]
