# Generated by Django 3.2 on 2021-06-14 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_company_name_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_size', models.CharField(choices=[('KNK', 'Канада'), ('USA', 'США'), ('RUS', 'Россия'), ('NDN', 'Нидерланды'), ('FRF', 'Франция'), ('ISI', 'Испания'), ('ITI', 'Италия'), ('AVA', 'Австрия'), ('UKU', 'Англия'), ('GER', 'Германия')], default='USA', max_length=5)),
                ('shirt_limit', models.CharField(choices=[('Отключен', 'Отключен'), ('1 день', '1 день'), ('3 дня', '3 дня'), ('1 неделя', '1 неделя'), ('2 недели', '2 недели'), ('1 месяц', '1 месяц'), ('2 месяца', '2 месяца')], default='Отключен', max_length=15)),
                ('number_phonesq', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номер',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='name_company',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='numberssssq',
        ),
        migrations.AddField(
            model_name='number',
            name='shirt_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.company'),
        ),
    ]
