# Generated by Django 3.2 on 2021-06-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20210614_2329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='number',
            new_name='numberssssq',
        ),
    ]
