# Generated by Django 3.2.4 on 2021-06-14 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_remove_numberssssq_shirt_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberssssq',
            name='shirt_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.company'),
        ),
    ]
