# Generated by Django 3.2.4 on 2021-06-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_numberssssq_shirt_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberssssq',
            name='bool_number',
            field=models.BooleanField(default=True),
        ),
    ]
