# Generated by Django 3.2 on 2021-07-12 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_number_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_all',
            name='price_select',
            field=models.CharField(default='0', max_length=10000000),
        ),
        migrations.AddField(
            model_name='number_all',
            name='shirt_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.company'),
        ),
        migrations.AlterField(
            model_name='number_all',
            name='days_sizes',
            field=models.CharField(choices=[('none', 'none'), ('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four')], default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='number_all',
            name='hours_sizes',
            field=models.CharField(choices=[('none', 'none'), ('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five')], default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='number_all',
            name='monsday_sizes',
            field=models.CharField(choices=[('none', 'none'), ('one', 'one'), ('two', 'two')], default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='number_all',
            name='weeks_sizes',
            field=models.CharField(choices=[('none', 'none'), ('one', 'one'), ('two', 'two'), ('three', 'three')], default='none', max_length=5),
        ),
    ]
